---
- hosts: all

  tasks:
    - name: Create OpenShift Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace_name }}"

    - name: Create an Openshift Virtualization virtual machine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        namespace: "{{ namespace_name }}"
        name: "{{ virt_machine_name }}"
        instancetype:
          name: u1.medium
        preference:
          name: fedora
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
          networks:
            - name: default
              pod: {}
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/fedora:latest
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  # The default username is: fedora
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8TVghDy/PUIzksr8/Um03Hvqfc5Zf662OEEV8iZ9tJi0KcnJWNoAu29TxJad9Muv6IGV99x657+TRV+nZgExkRF1ZgL/Ko2xo6V7ORZkMePTb8MxU+afMwFAmpsPmwgGpzvP09XXgLA3XHdlyDXyFzMuPADAUetYOtt6IFda+i6Klj/DcXJZ78ZX3r/h50X0KM4hpKZaPsDd1kb5xhY6pyxF2LCQ4JkcHcFh07J+jharqpGU5FhVxE4IFdSh3Tn8Ozh6lgE9sTyjuK40R8Gwzuel1R2aFYkkwXzMXakDQaWvpP96a3aGQJYm3S5njj7OVJZy8KvWY9BqSipu+MqUQjYcORwAuTj/AG8CrBQTxAcco4P2F/kRtXm0imbToTkM7hZS0TaeyluifcYChoa1zazvlOAyVdYndt6Mmlr6XvkAWeJ9qtNY6rJ6CHeSCQtaVdEebxCofRBCJLJINKzuB6A6i9uVE96nywCumkkGZimy+LGGANBKNMI1E303aUDU= asalgado@asalgado-mac
              name: cloudinitdisk

    - name: Wait for the VM to be running
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: "{{ namespace_name }}"
        name: "{{ virt_machine_name }}"
        wait: true

    - name: Create a service in OCP to expose port 80 for the virt machine just created
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ virt_machine_name }}"
            namespace: "{{ namespace_name }}"
          spec:
            selector:
              kubevirt.io/domain: "{{ virt_machine_name }}"
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 80
                protocol: TCP

    - name: Create a route in OCP to expose the service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ virt_machine_name }}"
            namespace: "{{ namespace_name }}"
          spec:
            to:
              kind: Service
              name: "{{ virt_machine_name }}"
            port:
              targetPort: http
            wildcardPolicy: None