---
- name: Create/Ensure exists namespace and VM
  hosts: localhost

  vars_files:
    - vm_vars/vms.yml

  tasks:
    - name: Create/Ensure exists OpenShift Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace_name }}"

    - name: Create an Openshift Virtualization virtual machine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        namespace: "{{ namespace_name }}"
        name: "{{ virt_machine_name }}"
        instancetype:
          name: u1.medium
        preference:
          name: fedora
        spec:
          template:
            metadata:
              labels:
                vm.kubevirt.io/name: "{{ vm_name }}"
          domain:
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - name: rootdisk
              containerDisk:
                image: quay.io/containerdisks/fedora
            - cloudInitNoCloud:
                userData: |
                  #cloud-config
                  chpasswd:
                    expire: false
                  password: {{ ssh_vm_password }}
                  user: {{ ssh_vm_username }}
              name: cloudinitdisk

    - name: Wait for the VM to be running
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: "{{ namespace_name }}"
        name: "{{ vm_name }}"
        wait: true