---
- hosts: all
  vars:
    namespace_name: "demo-ocpvirt-webapp"

  tasks:
    - name: Create OpenShift Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace_name }}"

    - name: Create an Openshift Virtualization virtual machine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        namespace: "{{ namespace_name }}"
        name: "webapp"
        instancetype:
          name: u1.medium
        preference:
          name: fedora
