---
- name: Manage VMs in Openshift Virtualization
  hosts: all

  vars_files:
    - vm_vars/vms.yml

  tasks:
    - name: Get all existing vms in Openshift Virtualization
      redhat.openshift_virtualization.kubevirt_vm_info:
      register: vm_list

    - name: Create a list of VM names and namespaces with custom attribute names
      ansible.builtin.set_fact:
        vm_name_namespace_list: "{{ vm_name_namespace_list | default([]) + [ {'vm_name': item.metadata.name, 'namespace_name': item.metadata.namespace } ] }}"
      loop: "{{ vm_list.resources }}"

    - name: Debug the list of VM names and namespaces with custom attribute names
      ansible.builtin.debug:
        var: vm_name_namespace_list