---
- name: Manage VMs in Openshift Virtualization
  hosts: all

  vars_files:
    - vm_vars/vms.yml

  tasks:
    - name: Get all existing vms in Openshift Virtualization
      redhat.openshift_virtualization.kubevirt_vm_info:
      register: vm_list

    - name: Create a list of VM names and namespaces with custom attribute names
      ansible.builtin.set_fact:
        vm_name_namespace_list: "{{ vm_name_namespace_list | default([]) + [ {'vm_name': item.metadata.name, 'namespace_name': item.metadata.namespace } ] }}"
      loop: "{{ vm_list.resources }}"
      no_log: true

    - name: Debug the list of VM names and namespaces with custom attribute names
      ansible.builtin.debug:
        var: vm_name_namespace_list

    - name: Create a list of VMs from vars/vms.yml
      ansible.builtin.set_fact:
        vms_from_vars: "{{ vms_from_vars | default([]) + [{'vm_name': item.vm_name, 'namespace_name': item.namespace_name} ]  }}"
      loop: "{{ vms }}"

    - name: Debug
      ansible.builtin.debug:
        var: vms_from_vars

    - name: Find VMs not included in vars/vms.yml
      ansible.builtin.set_fact:
        missing_vms: "{{ vm_name_namespace_list | difference(vms_from_vars) }}"

    - name: Debug the list of missing VMs
      ansible.builtin.debug:
        var: missing_vms