---
- name: Manage VMs in Openshift Virtualization
  hosts: all

  vars_files:
    - vm_vars/vms.yml

  tasks:
    - name: Get all existing vms in Openshift Virtualization
      redhat.openshift_virtualization.kubevirt_vm_info:
      register: vm_list

    - debug:
        msg: "{{ item.metadata.name }}" 
      loop: vm_list.resources