---
- hosts: all

  tasks:
    - name: Create a service in OCP to expose port 80 for the virt machine just created
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ virt_machine_name }}"
            namespace: "{{ namespace_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ virt_machine_name }}"
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: "{{ app_source_port }}"
                protocol: TCP

    - name: Create a route in OCP to expose the service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ virt_machine_name }}"
            namespace: "{{ namespace_name }}"
          spec:
            to:
              kind: Service
              name: "{{ virt_machine_name }}"
            port:
              targetPort: http
            wildcardPolicy: None