---
- ansible.builtin.debug:
    msg: "Removing will start soon"

- name: Remove VMs if needed
  redhat.openshift_virtualization.kubevirt_vm:
    state: absent
    namespace: "{{ item.namespace_name }}"
    name: "{{ item.vm_name }}"
  loop: "{{ missing_vms }}"